version: '2'
services:
  replicate:
    build: .
    environment:
      TARGET_URL: "localhost"
      TARGET_PORT: "9000"
      HOST_URL: "localhost"
      HOST_PORT: "5984"
      DB_NAME: "blinkbox_files"
    links:
      - couch-db

  couch-db:
    image: klaemo/couchdb:2.0-single
    ports:
      - '9001:5984'
